{application,gproc,
             [{description,"GPROC"},
              {vsn,"0.01"},
              {id,"GPROC"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{gproc_app,[]}},
              {modules,[gproc,gproc_app,gproc_dist,gproc_eqc,gproc_init,
                        gproc_lib,gproc_sup]}]}.
